[build]
  command = """
    sudo apt-get update && sudo apt-get install -y libmysqlclient-dev
    export CFLAGS="$CFLAGS -I/usr/include/mysql"
    export LDFLAGS="$LDFLAGS -L/usr/lib/mysql"
    pip install -r requirements.txt
  """
  publish = "your_publish_directory" # Replace with your actual publish directory

[build.environment]
  PYTHON_VERSION = "your_python_version" # Replace with your desired Python version
  MYSQLCLIENT_CFLAGS = "-I/usr/include/mysql"
  MYSQLCLIENT_LDFLAGS = "-L/usr/lib/mysql"
