[build]
  command = """
    sudo apt-get update && sudo apt-get install -y libmysqlclient-dev pkg-config curl
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    export CARGO_HOME="$HOME/.cargo"
    export PATH="$PATH:$CARGO_HOME/bin"
    rustup toolchain install stable
    rustup default stable
    source "$CARGO_HOME/env"
    export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig"
    export CFLAGS="-I/usr/include/mysql" # Explicitly set CFLAGS
    export LDFLAGS="-L/usr/lib/mysql" # Explicitly set LDFLAGS
    pip install -r requirements.txt
  """
  publish = "staticfiles"
