[build]
  command = """
    sudo apt-get update && sudo apt-get install -y libmysqlclient-dev
    export CFLAGS="$CFLAGS -I/usr/include/mysql"
    export LDFLAGS="$LDFLAGS -L/usr/lib/mysql"
    pip install -r requirements.txt
  """
  publish = "staticfiles" # Replace with your actual publish directory

[build.environment]
  PYTHON_VERSION = "3.13" # Replace "your_python_version" with "3.13" or your desired version
