[build]
  command = """
    sudo apt-get update && sudo apt-get install -y libmysqlclient-dev pkg-config curl
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    export CARGO_HOME="$HOME/.cargo"
    export PATH="$PATH:$CARGO_HOME/bin"
    rustup toolchain install stable
    rustup default stable
    source "$CARGO_HOME/env"
    echo "Current PATH: $PATH" # Add this line to check the PATH
    export PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig"
    export CFLAGS="$CFLAGS -I/usr/include/mysql"
    export LDFLAGS="$LDFLAGS -L/usr/lib/mysql"
    pip install -r requirements.txt
  """
  publish = "your_publish_directory"
